// cPanel / Phusion Passenger startup shim.
// The production build is generated by .cpanel.yml into .output/server/index.mjs.
// Keep this file at the repository root so cPanel can use app.js as the startup file.
import "./.output/server/index.mjs";
