import { useEffect, useState, type ReactNode } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';

export const contacts = [
  {name:'Avery Chen', company:'Evergreen Studio', email:'avery@example.com', phone:'+1 (202) 555-0101', source:'Website', tags:'High intent', stage:'Qualified', activity:'Replied 8 min ago', owner:'Alex', value:8400},
  {name:'Jordan Blake', company:'Northline Homes', email:'jordan@example.com', phone:'+1 (202) 555-0102', source:'Google Ads', tags:'Real estate', stage:'Meeting', activity:'Booked 24 min ago', owner:'Sam', value:4200},
  {name:'Taylor Morgan', company:'Atlas Wellness', email:'taylor@example.com', phone:'+1 (202) 555-0103', source:'Referral', tags:'Priority', stage:'Proposal', activity:'Opened email 1h ago', owner:'Alex', value:6750},
  {name:'Casey Rivera', company:'Fieldwork Co.', email:'casey@example.com', phone:'+1 (202) 555-0104', source:'Social', tags:'New lead', stage:'Qualified', activity:'Form submitted 2h ago', owner:'Jamie', value:3200},
];
export type Contact = typeof contacts[number];
export const money = (n:number) => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
export function Badge({children, muted=false}:{children:ReactNode;muted?:boolean}) { return <span className={`inline-flex rounded px-2 py-1 text-[10px] font-semibold ${muted?'bg-muted text-muted-foreground':'bg-primary/10 text-primary'}`}>{children}</span> }
export function Stats({items}:{items:[string,string][]}) { return <div className="grid grid-cols-2 gap-x-5 gap-y-6 border-y border-border py-5 sm:grid-cols-4">{items.map(([label,value])=><div key={label} className="min-w-0"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 break-words text-2xl font-semibold tabular-nums">{value}</p></div>)}</div> }
export function Bars({values=[32,45,38,62,51,70,65,84,74,95], label='Performance', secondary=false}:{values?:number[];label?:string;secondary?:boolean}) {return <figure aria-label={label} className="min-w-0"><div className="flex h-32 items-end gap-2 border-b border-border pt-4">{values.map((v,i)=><div key={i} className={`flex-1 rounded-t-sm ${secondary?'bg-muted-foreground/50':'bg-primary/75'} transition-all duration-500 hover:bg-primary`} style={{height:`${v}%`}} title={`${i+1}: ${v}`}/>)}</div><figcaption className="mt-3 flex justify-between text-[10px] text-muted-foreground"><span>Period start</span><span>{label}</span><span>Period end</span></figcaption></figure>}
export function SectionTitle({children, action}:{children:ReactNode;action?:ReactNode}) {return <div className="flex flex-wrap items-center justify-between gap-3 py-5"><h4 className="text-sm font-semibold">{children}</h4>{action}</div>}
export function DemoForm({title, open, onClose, onSave, fields=['Name']}:{title:string;open:boolean;onClose:()=>void;onSave:(values:Record<string,string>)=>void;fields?:string[]}) {return <Dialog open={open} onOpenChange={v=>{if(!v)onClose()}}><DialogContent className="max-h-[85svh] overflow-y-auto"><DialogTitle>{title}</DialogTitle><DialogDescription>Demo workspace only. No real messages, charges or external changes.</DialogDescription><form className="space-y-4" onSubmit={e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget).entries()) as Record<string,string>;onSave(data);onClose()}}>{fields.map(f=><label key={f} className="block text-sm">{f}<Input autoComplete="off" className="mt-2 min-h-11" name={f} required maxLength={160} type={f==='Amount'?'number':f==='Email'?'email':f==='Date'?'date':'text'} min={f==='Amount'?1:undefined}/></label>)}<Button type="submit" className="min-h-11 w-full">Save to demo</Button></form></DialogContent></Dialog>}
export function Count({value,suffix='',prefix=''}:{value:number;suffix?:string;prefix?:string}) {const [n,setN]=useState(value);useEffect(()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){setN(value);return}let frame=0;const start=performance.now();const run=(now:number)=>{const p=Math.min((now-start)/650,1);setN(Math.round(value*(1-Math.pow(1-p,3))));if(p<1)frame=requestAnimationFrame(run)};frame=requestAnimationFrame(run);return()=>cancelAnimationFrame(frame)},[value]);return <>{prefix}{n.toLocaleString()}{suffix}</>}